version:                                   "3"
services:
  bifrostpostgres:
      image:                               postgres
      container_name:                      postgres-bifrost
      restart:                             unless-stopped
      volumes:
        - ~/stellar/bifrost/postgresql:/var/lib/postgresql/data
      environment:
        POSTGRES_USER:                     stellar
        POSTGRES_PASSWORD:                 password
        POSTGRES_DB:                       bifrostdb
      networks:
          - stellarbitcoin_default
          - stellarethereum_default
          - stellarcorehorizon_default
          - default

  bifrost:
      build:                               ./bifrost-docker
      container_name:                      stellar-bifrost
      volumes:
        - ~/stellar/bifrost:/opt/bifrost
      restart:                             unless-stopped
      depends_on:
        - bifrostpostgres
      environment:
        POSTGRES_USER:                     stellar
        POSTGRES_PASSWORD:                 password
        MASTER_PUBLIC_KEY:                 "xpub6C79eBsW2XQbzfXFsRv51Lac6Ckx5nyqf9cUmFr1fuAEHGXmpq8oPNMqCpH1jTdwP3s5SD644R8KK4cVytk9Jxcxcb7JsfNxcGNRbG5q4pq"
        BIFROST_BITCOIN_RPC_SERVER:        "bitcoind:18332"
        RPC_USER:                          "user"
        RPC_PASS:                          "password"
        TESTNET:                           "true"
        MINIMUM_VALUE_BTC:                 "0.00001"
        BIFROST_ETHEREUM_RPC_SERVER:       "ethereum:8545"
        NETWORK_ID:                        "4"
        MINIMUM_VALUE_ETH:                 "0.00001"
        BIFROST_STELLAR_ISSUER_PUBLIC_KEY: "GDBTRP7XKRJ5PZJ25O3FLAHFMTQOSUWLSNZCOEEAR73TWDZENODNGDCS"
        BIFROST_STELLAR_SIGNER_SECRET_KEY: "SCW6UIBPNI5IQI55DGIAPCYDFNF7RWX4DYTTC253XNQ7LTPZASKXQIPI"
        TOKEN_ASSET_CODE:                  "LMB"
        NEEDS_AUTHORIZE:                   "false"
        BIFROST_STELLAR_HORIZON:           "http://stellarhorizon:8000"
        NETWORK_PASSPHRASE:                "Test SDF Network ; September 2015"
        BIFROST_DB_TYPE:                   "postgres"
        BIFROST_DB_DSN:                    "postgres://stellar:password@bifrostpostgres/bifrostdb?sslmode=disable"
        BIFROST_DB_HOST:                   "bifrostpostgres"
      ports:
        - "8800:8800"
      networks:
          - stellarbitcoin_default
          - stellarethereum_default
          - stellarcorehorizon_default
          - default

networks:
  stellarbitcoin_default:
    external:                              true
  stellarethereum_default:
    external:                              true
  stellarcorehorizon_default:
    external:                              true
